version: '3.8'

volumes:
  code:
  db:

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - code:/code
    working_dir: /code
    command: /bin/sh
    tty: true
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
