version: '3.8'

volumes:
  prismagql:
  db:

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - prismagql:/prismagql
    working_dir: /prismagql
    command: /bin/sh
    tty: true
  db:
    image: postgres:12.6
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
